FROM fluent/fluentd:edge-debian
USER root
#RUN ["gem", "install", "fluent-plugin-elasticsearch", "--no-document", "--version", "1.9.2"]
RUN ["gem", "install", "fluent-plugin-elasticsearch", "--no-document", "--version", "1.9.2"]
USER fluent
