FROM fluent/fluentd:v1.16-debian-1
USER root
#RUN ["gem", "install", "fluent-plugin-elasticsearch", "--no-document", "--version", "1.9.2"]
RUN ["gem", "install", "fluent-plugin-elasticsearch", "--no-document", "--version", "1.9.2"]
USER fluent
