"""Init database

Revision ID: 227f3dd49c44
Revises: 
Create Date: 2022-08-09 17:24:41.857729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '227f3dd49c44'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coffee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('origin', sa.String(length=200), nullable=True),
    sa.Column('intensifier', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.ARRAY(sa.String(), as_tuple=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('has_sale', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('address', sa.JSON(), nullable=True),
    sa.Column('coffee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coffee_id'], ['coffee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('coffee')
    # ### end Alembic commands ###
