version: "3"
services:
  app:
    build:
      context: app
    stop_signal: SIGKILL
    ports:
      - 5000:5000
    links:
      - postgres
    volumes:
      - ./app/app.py:/var/server/app.py
    networks:
      - net

  postgres:
    image: postgres
    restart: always
    command:
      postgres -c log_statement=all -c logging_collector=on -c log_destination=stderr -c log_directory=/logs
    environment:
      POSTGRES_DB: "my_db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data
      - ./logs:/logs
    networks:
      - net


networks:
  net:
    driver: bridge

